build:
	g++ -g ../*.cpp ../libs/*.cpp -std=c++2a -o main_app

run:
	./main_app

build_and_run:
	g++ -g ../*.cpp -std=c++2a -o main_app
	./main_app

run_x01:
	g++ -g ../x01*.cpp ../libs/libs1/*.cpp -std=c++2a -o main_app
	./main_app

run_x02:
	g++ -g ../x02*.cpp ../libs/libs2/*.cpp -std=c++2a -o main_app
	./main_app

run_x03:
	g++ -g ../x03*.cpp ../libs/libs3/*.cpp -std=c++2a -o main_app
	./main_app

run_x04:
	g++ -g ../x04*.cpp ../libs/libs4/*.cpp -std=c++2a -o main_app
	./main_app
