build:
	g++ -g ../*.cpp ../libs/*.cpp -std=c++2a -o main_app.out

run:
	./main_app.out

build_and_run:
	g++ -g ../*.cpp -std=c++2a -o main_app.out
	./main_app.out

run_x01:
	g++ -g ../x01*.cpp ../libs/*.cpp -std=c++2a -o main_app.out
	./main_app.out

run_x02:
	g++ -g ../x02*.cpp ../libs2/*.cpp -std=c++2a -o main_app.out
	./main_app.out

run_x03:
	g++ -g ../x03*.cpp ../libs2/*.cpp -std=c++2a -o main_app.out
	./main_app.out

run_x04:
	g++ -g ../x04*.cpp ../libs2/*.cpp -std=c++2a -o main_app.out
	./main_app.out

run_x05:
	g++ -g ../x05*.cpp ../libs3/*.cpp -std=c++2a -o main_app.out
	./main_app.out

run_x06:
	g++ -g ../x06*.cpp ../libs4/*.cpp -std=c++2a -o main_app.out
	./main_app.out

run_x07:
	g++ -g ../x07*.cpp ../libs5/*.cpp -std=c++2a -o main_app.out
	./main_app.out

run_x08:
	g++ -g ../x08*.cpp ../libs6/*.cpp -std=c++2a -o main_app.out
	./main_app.out

run_x09:
	g++ -g ../x09*.cpp ../libs7/*.cpp -std=c++2a -o main_app.out
	./main_app.out

run_x10:
	g++ -g ../x10*.cpp ../libs8/*.cpp -std=c++2a -o main_app.out
	./main_app.out

run_x11:
	g++ -g ../x11*.cpp ../libs9/*.cpp -std=c++2a -o main_app.out
	./main_app.out

run_x12:
	g++ -g ../x12*.cpp ../libs10/*.cpp -std=c++2a -o main_app.out
	./main_app.out

run_x13:
	g++ -g ../x13*.cpp ../libs11/*.cpp -std=c++2a -o main_app.out
	./main_app.out

run_x14:
	g++ -g ../x14*.cpp ../libs11/*.cpp -std=c++2a -o main_app.out
	./main_app.out