build:
	g++ -g ../*.cpp ../libs/*.cpp -std=c++2a -o main_app

run:
	./main_app

build_and_run:
	g++ -g ../*.cpp -std=c++2a -o main_app
	./main_app

run_x01:
	g++ -g ../x01*.cpp -std=c++2a -o main_app
	./main_app

run_x02:
	g++ -g ../x02*.cpp -std=c++2a -o main_app
	./main_app

run_x03:
	g++ -g ../x03*.cpp -std=c++2a -o main_app
	./main_app

run_x04:
	g++ -g ../x04*.cpp -std=c++2a -o main_app
	./main_app

run_x05:
	g++ -g ../x05*.cpp -std=c++2a -o main_app
	./main_app

run_x06:
	g++ -g ../x06*.cpp -std=c++2a -o main_app
	./main_app

run_x07:
	g++ -g ../x07*.cpp -std=c++2a -o main_app
	./main_app

run_x08:
	g++ -g ../x08*.cpp -std=c++2a -o main_app
	./main_app
